#!/usr/bin/env bash
# Script to install and configure nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i 's/listen.*80 default server/listen 80 default_server;\n\tlisten [::]:80 default_server;/' /etc/nginx/sites-available/default
sudo echo 'Hello World!' > /var/www/html/index.html
sudo service nginx stop
sudo service nginx start
