#!/usr/bin/env bash
# Bash script to configure the nginx server for a 301 redirect
sudo apt-get update
sudo apt-get install -y nginx
echo 'Hello World' > /var/www/html/index.html
config="server {
	listen 80 default_server;
        listen [::]:80 default_server;

        server_name _;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	add_header X-Served-By viclinstoriel;

	location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGU1wu4;
        }
}"
echo $config > /etc/nginx/sites-available/default
sudo service nginx stop
sudo service nginx start
