#!/usr/bin/env bash
# Bash script to configure the nginx server for a 301 redirect
apt-get -y update
apt-get -y nginx
echo 'Hello World' > /var/www/html/index.nginx-debian.html
sed -i '/server_name _;/a \\n\trewrite ^\/redirect_me \/ permanent;'  /etc/nginx/sites-available/default
service nginx start
