#!/usr/bin/env bash
# Bash script to configure the nginx server for a 301 redirect
sudo apt-get -y update
sudo apt-get -y nginx
sudo echo 'Hello World' > /var/www/html/index.nginx-debian.html
sudo echo "ceci n'est pas une page" > /var/www/html/custom404error.html
sudo sed -i 's/server_name _;/server_name _;\n\terror_page 404 \/custom404error.html;\n\n\tlocation \/custom404error.html {\n\t\tinternal;\n\t}/' /etc/nginx/sites-available/default
sudo sed -i 's.server_name _;.server_name _;\n\n\tlocation ~ /redirect_me {\n\t\treturn 301 https://www\.youtube\.com/watch?v=QH2-TGU1wu4;\n\t}.' /etc/nginx/sites-available/default
sudo service nginx stop
sudo service nginx start
