#!/usr/bin/env bash
#Bash script that displays content of the file /etc/passwd

FILENAME="/etc/passwd"
while IFS=: read -r username password userid groupid comment homedir cmdshell
do
        echo "The user $username is part of the $groupid gang,"\
		"lives in $homedir and rides $cmdshell."\
		"$userid's place is protected by the passcode $password,"\
		"more info about the user here: $comment"
done < $FILENAME
