#!/usr/bin/env bash
# Program to print numbers 20 times with a while loop and case statement

i=1

while [ "$i" -le 20 ]; do
    case $i in
        4)
	    echo "$i"
	    echo "bad luck from china"
        ;;
	9)
	    echo "$i"
	    echo "bad luck from japan"
	;;
	17)
	    echo "$i"
	    echo "bad luck from italy"
	;;
	*)
	     echo "$i"
	;;
    esac
    i=$((i + 1));
done
